import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from 'sonner'
import { neobrutalism } from '@clerk/themes'
import AppWalletProvider from './wallet/AppWalletProvider'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'PLAYapecoin',
  description: 'Generated by create next 18+ Entertainment',
  icons: {
    icon: './favicon.ico',
  }
}
  


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: neobrutalism }}>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute="class" forcedTheme="dark">
            <Toaster theme='light' position='bottom-center'/>
            <AppWalletProvider>{children}</AppWalletProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
